### ISSUE TITLE
提供一个可访问的文件URL或者BASE64_URL进行解析。

### ISSUE THREAD

**Issue by wohui** [LLM-Red-Team/spark-free-api#12]
我已经使用了base64进行转换了，为什么还是说不合法呢
data = {
        "model": "kimi",
        "messages": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "file",
                        "file_url": {
                            "url": base64url_encoded
                        }
                    },
                    {
                        "type": "text",
                        "text": "文档里说了什么？"
                    }
                ]
            }
        ],
        "use_search": False
    }

**Comment by Vinlic** [comment]
BASE64_URL是带有data:[mime];base64,头部的，不是纯base64
data:image/png;base64,......
