### ISSUE TITLE
原生的多轮对话 首次传入conversation_id 为None，结果报错

### ISSUE THREAD

**Issue by shyBoy-ico** [LLM-Red-Team/spark-free-api#7]
报错 {'code': -2000, 'message': 'Params body.conversation_id invalid', 'data': None}

{
            "model": "spark",
            # 如果您想获得原生的多轮对话体验，可以传入首轮消息获得的id，来接续上下文，注意如果使用这个，首轮必须传none，否则第二轮会出现[belongerr]！
            "conversation_id": None,
            "messages": [
                {
                    "role": "user",
                    "content": "你是谁？"
                }
            ],
            # 如果使用SSE流请设置为true，默认false
            "stream": False
}

**Comment by Vinlic** [comment]
使用字符串"none"

**Comment by shyBoy-ico** [comment]
谢谢，可以啦
