### ISSUE TITLE
为什么我提问回答是这个格式

### ISSUE THREAD

**Issue by shyBoy-ico** [LLM-Red-Team/spark-free-api#8]
第一次回答，格式正确，如下

{'id': '376634164:cht000b4927@dx18ff0a2aebfb81a560', 'model': 'spark', 'object': 'chat.completion', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '这份文件是安徽天禾律师事务所针对科大讯飞股份有限公司2023年第三次临时股东大会的法律意见书。法律意见书主要包含以下几个方面的内容：\n\n1. 对本次股东大会的召集、召开程序及召集人资格进行审查，认为符合相关法律法规和公司章程规定，会议召集人资格合法有效。\n\n2. 对出席本次股东大会的股东、董事、监事、高级管理人员等人员的资格进行审查，认为其与会资格合法有效。\n\n3. 对本次股东大会的表决程序和结果进行审查，包括现场投票和网络投票，认为表决程序和结果符合法律法规和公司章程的规定，决议合法有效。\n\n4. 综合以上审查，安徽天禾律师事务所给出结论意见，认为科大讯飞股份有限公司2023年第三次临时股东大会的相关事宜符合《公司法》《股东大会规则》等相关法律、法规和《公司章程》的规定，本次股东大会决议合法有效。\n\n该法律意见书由安徽天禾律师事务所负责人卢贤榕签字，经办律师为费林森和盛建平。'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 1, 'completion_tokens': 1, 'total_tokens': 2}, 'created': 1717729145}
第二次回答，格式如下

{'id': '376634164:cht000b6763@dx18ff0a422a79a4b560', 'model': 'spark', 'object': 'chat.completion', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '```allTool\n{"payload":{"plugins":{"text":[{"deskToolName":"联网搜索","role":"assistant","content_type":"text","name":"ifly_search","invoked":{"plugin_id":"ifly_search","status_code":200,"plugin_ver":"","namespace":"ifly_search","status_msg":"Success","type":"local"},"status":"finished"}]}},"header":{"code":0,"message":"Success","sid":"cht000b6763@dx18ff0a422a79a4b560","status":0}}\n```\n```searchSource\n[{"index":1,"source":"http://static.cninfo.com.cn/finalpage/2023-12-16/1218635667.PDF","docid":"2023 年第三次临时股东大会的法律意见书 - 巨潮资讯网","document":"目前无法访问该链接的文件格式"},{"index":2,"source":"http://file.finance.sina.com.cn/211.154.219.97:9494/MRGG/CNSESZ_STOCK/2024/2024-5/2024-05-14/10203845.PDF","docid":"2023 年年度股东大会的法律意见书","document":"目前无法访问该链接的文件格式"},{"index":3,"source":"https://finance.sina.com.cn/roll/2023-12-16/doc-imzycrup4258782.shtml","docid":"科大讯飞股份有限公司2023年第三次临时股东大会决议公告 ...","document":"滚动新闻 \\u0026gt; 正文          行情 股吧 新闻 外汇 新三板                                 科大讯飞股份有限公司2023年第三次临时股东大会决议公告             科大讯飞股份有限公司2023年第三次临时股东大会决议公告          2023年12月15日 09:15 上海证券报                                                   证券代码：002230 证券简称：科大讯飞 公告编号：2023-075\\n科大讯飞股份有限公司\\n2023年第三次临时股东大会决议公告\\n本公司及董事会全体成员保证信息披露内容真实、准确和完整，没有虚假记载、误导性陈述或者重大遗漏。\\n特别提示\\n1.本次股东大会未出现否决议案的情形。\\n2.本次股东大会未涉及变更前次股东大会决议。\\n一、会议召开和出席情况\\n1、会议召开时间：\\n现场会议开始时间：2023年12月15日（星期五）14:30；\\n网络投票时间：通过深圳证券交易所交易系统进行网络投票的具体时间为2023年12月15日的交易时间，即9:15一9:25，9:30一11:30 和13:00一15:00；通过深圳证券交易所互联网投票系统进行网络投票的具体时间为2023年12月15日9:15至15：00期间的任意时间。\\n2、现场会议召开地点：安徽省合肥市高新开发区望江西路666号公司A1楼会议室\\n3、会议召开方式：本次股东大会采取现场投票表决与网络投票表决相结合的方式\\n4、会议召集人：公司董事会\\n5、会议主持人：董事长刘庆峰先生\\n6、本次会议的召集、召开与表决程序符合《公司法》《上市公司股东大会规则》等有关法律、行政法规、部门规章、规范性文件和公司章程的规定。\\n7、会议出席情况：通过现场和网络投票的股东266人，代表股份695,444,756股，占上市公司总股份的30.0319％。其中：通过现场投票的股东40人，代表股份529,683,276股，占上市公司总股份的22.8737％；通过网络投票的股东226人，代表股份165,761,480股，占上市公司总股份的7.1582％。\\n公司董事会秘书及董事、监事、高级管理人员、律师等出席或列席了本次股东大会。\\n二、提案审议表决情况\\n会议按照召开2023年第三次临时股东大会通知的议题进行，无否决或取消提案的情况。本次股东大会议案采用现场投票与网络投票相结合的表决方式，审议并通过以下议案：\\n1、审议并获得有效表决权股份总数的三分之二以上通过《关于回购注销部分已授予限制性股票的议案》。\\n该议案的表决结果为：同意695,426,256股，占出席会议所有股东所持股份的99.9973％；反对18,500股，占出席会议所有股东所持股份的0.0027％；弃权0股，占出席会议所有股东所持股份的0.0000％。\\n中小股东总表决情况：同意117,771,843股，占出席会议的中小股东所持股份的99.9843％；反对18,500股，占出席会议的中小股东所持股份的0.0157％；弃权0股，占出席会议的中小股东所持股份的0.0000％。\\n2、审议通过《独立董事制度》。\\n该议案的表决结果为：同意671,545,984股，占出席会议所有股东所持股份的96.5635％；反对23,898,772股，占出席会议所有股东所持股份的3.4365％；弃权0股，占出席会议所有股东所持股份的0.0000％。\\n中小股东总表决情况：同意93,891,571股，占出席会议的中小股东所持股份的79.7108％；反对23,898,772股，占出席会议的中小股东所持股份的20.2892％；弃权0股，占出席会议的中小股东所持股份的0.0000％。\\n3、审议并获得有效表决权股份总数的三分之二以上通过《关于变更注册资本及修订〈公司章程〉的议案》。\\n该议案的表决结果为：同意695,426,256股，占出席会议所有股东所持股份的99.9973％；反对18,500股，占出席会议所有股东所持股份的0.0027％；弃权0股，占出席会议所有股东所持股份的0.0000％。\\n中小股东总表决情况：同意117,771,843股，占出席会议的中小股东所持股份的99.9843％；反对18,500股，占出席会议的中小股东所持股份的0.0157％；弃权0股，占出席会议的中小股东所持股份的0.0000％。\\n三、律师出具的法律意见\\n安徽天禾律师事务所费林森律师、盛建平律师到会见证本次股东大会，并出具了法律意见书，认为：公司2023年第三次临时股东大会的召集与召开、参加会议人员与召集人资格、表决程序与表决结果等相关事宜符合《公司法》《股东大会规则》等相关法律、法规和《公司章程》的规定，本次股东大会决议合法有效。\\n四、备查文件\\n1、经与会董事和记录人签字确认并加盖董事会印章的股东大会决议；\\n2、安徽天禾律师事务所出具的《关于公司2023年第三次临时股东大会的法律意见书》。\\n科大讯飞股份有限公司\\n董 事 会\\n二〇二三年十二月十六日\\n证券代码：002230 证券简称：科大讯飞 公告编号：2023-076\\n科大讯飞股份有限公司\\n关于回购注销部分已授予限制性股票减资\\n暨通知债权人的公告\\n本公司及董事会全体成员保证信息披露内容真实、准确和完整，没有虚假记载、误导性陈述或者重大遗漏。\\n科大讯飞股份有限公司（以下简称“公司”）第六届董事会第五次会议、第六届监事会第五次会议以及2023年第三次临时股东大会，分别审议通过了有关回购注销部分已授予限制性股票的议案。由于公司第二期限制性股票激励计划和2021年股票期权与限制性股票激励计划有部分员工因离职失去激励对象资格等原因，公司将对相关激励对象已授予但尚未解除限售的相应部分的限制性股票进行回购注销。\\n本次回购注销已授予但尚未解除限售的限制性股票总313,360股，占公司总股本2,315,689,153股的比例为0.0135%。其中，回购注销公司第二期限制性股票激励计划的相关激励对象已授予但尚未解除限售的相应部分的第二期限制性股票合计135,720股，该等股份占公司第二期限制性股票激励计划所涉及的标的限制性股票的比例为0.51%，占总股本的比例为0.0059%；回购注销2021年股票期权与限制性股票激励计划之限制性股票激励对象已授予但尚未解除限售的限制性股票合计177,640股，该等股份占公司2021年股票期权与限制性股票激励计划所涉及的标的限制性股票的比例为0.73%，占总股本的比例为0.0077%。公司股权激励计划的实施，对公司稳定骨干团队起到了积极的促进作用，激励对象离职率远低于人工智能行业平均水平，公司在激烈的人才竞争中继续保持了高端人才的稳定性。\\n公司本次回购注销上述人员已授予但尚未解除限售的限制性股票合计313,360股，资金总额7,095,052.80元。本次回购注销完成后，公司注册资本将随之发生变动。若本次回购注销实施期间，公司未发生其他注册资本变动事项，公司总股本将由2,315,689,153股减至2,315,375,793股。"},{"index":4,"source":"https://guba.eastmoney.com/news,002230,1426059802.html","docid":"科大讯飞:安徽天禾律师事务所关于公司2023年年度股东大会 ...","document":"股吧首页 \\u0026gt; 科大讯飞吧 \\u0026gt; 帖子正文             返回科大讯飞吧 \\u0026gt;                   科大讯飞:安徽天禾律师事务所关于公司2023年年度股东大会的法律意见书                   科大讯飞资讯                   2024-05-13 19:29:14                                    1\\n2\\nA                        大中小\\n公告日期：2024-05-14\\n安徽天禾律师事务所\\n关于科大讯飞股份有限公司\\n2023 年年度股东大会的法律意见书\\n天律意 2024 第 01071 号\\n致：科大讯飞股份有限公司\\n根据《中华人民共和国公司法》（下称“《公司法》”）、《中华人民共和国证券法》（下称“《证券法》”）、中国证券监督管理委员会《上市公司股东大会规则》（下称“《股东大会规则》”）以及《科大讯飞股份有限公司章程》（下称“《公司章程》”）的有关规定，安徽天禾律师事务所接受科大讯飞股份有限公司（下称“公司”）的委托，指派本所费林森、盛建平律师（下称“天禾律师”）出席公司 2023 年年度股东大会（下称“本次股东大会”），并对本次股东大会相关事项进行见证，出具法律意见。\\n本法律意见书是天禾律师根据对本次股东大会事实的了解及对我国现行法律、法规和规范性文件的理解而出具的。\\n天禾律师同意将本法律意见书作为本次股东大会的法定必备文件予以公告，并依法对所出具的法律意见书承担责任。\\n天禾律师根据《证券法》相关规定的要求，按照律师行业公认的业务标准、道德规范和勤勉尽责精神，对本次股东大会的召集、召开、与会人员资格、表决程序及其他相关法律问题发表如下意见：\\n一、关于本次股东大会的召集、召开程序及召集人资格\\n（一）经验证，根据公司第六届董事会第七次会议决议，公司于 2024 年 4\\n月 23 日在《中国证券报》《上海证券报》《证券日报》《证券时报》和巨潮资讯网（http://www.cninfo.com.cn）刊登了《关于召开 2023 年年度股东大会的通知》。\\n（二）本次股东大会现场会议于 2024 年 5 月 13 日下午 14:30 在安徽省合\\n肥市高新开发区望江西路 666 号公司科大讯飞公司会议室召开，本次股东大会由公司董事会召集，董事长刘庆峰先生主持。\\n（三）本次股东大会网络投票时间为：2024 年 5 月 13 日。其中，通过深\\n圳证券交易所交易系统进行网络投票的时间为 2024 年 5 月 13 日上午 9:15 至\\n9:25，9:30 至 11:30 和下午 13:00-15:00；通过深圳证券交易所互联网投票系统\\n进行网络投票的时间为 2024 年 5 月 13 日上午 9:15 至下午 15:00 的任意时间。\\n天禾律师认为，本次股东大会的召集、召开程序符合法律、法规、《股东大会规则》及《公司章程》规定，会议召集人资格合法有效。\\n二、关于出席本次股东大会会议人员的资格\\n本次股东大会采取现场表决、网络投票相结合的方式，出席本次股东大会会议人员有：\\n（一）出席本次股东大会现场会议的股东及股东代理人、通过网络投票表决的股东共计 312 人，共代表公司股份 720,958,759 股，占公司股份总数的\\n31.1379%，其中：\\n1、出席现场会议的股东及股东代理人 53 人，代表公司股份 305,537,431\\n股，占公司股份总数的 13.1960%，均为 2024 年 5 月 6 日下午收市后，在中国\\n证券登记结算有限责任公司深圳分公司登记在册的公司股东。股东本人出席\\n的，均出示了本人的身份证明文件和持股凭证，股东代理人出席的除出示前述文件外，还出具了授权委托书及代理人的身份证明文件。\\n2、以网络投票方式参会的股东 259 人，代表公司股份 415,421,328 股，占\\n公司股份总数的 17.9419%，参与网络投票的股东的身份均获得深圳证券交易所系统的认证。\\n（二）公司部分董事、监事、高级管理人员。\\n（三）天禾律师。\\n经验证，上述人员参加本次股东大会符合法律、法规、《股东大会规则》和《公司章程》的规定，其与会资格合法有效。\\n三、关于本次股东大会的表决程序、表决结果\\n经天禾律师核查，公司本次股东大会对列入通知的议案作了审议，并以记名投票方式进行了现场和网络投票表决。\\n（一）表决程序\\n1、经本所律师验证，现场出席本次股东大会的有表决权的股东及股东代理人以记名投票方式对公告中列明的议案进行了表决。\\n2、参与网络投票的股东通过深圳证券交易系统和互联网投票系统（http://wltp.cninfo.com.cn），以记名投票方式按《深圳证券交易所上市公司股东大会网络投票实施细则》规定的程序对公告中列明的议案进行投票。网络投票结束后，深圳证券信息有限公司向公司提供了本次股东大会网络投票结果。"}]\n```\n```allTool\n{"payload":{"plugins":{"text":[{"deskToolName":"联网搜索","role":"tool","content_type":"text","name":"ifly_search","invoked":{"plugin_id":"ifly_search","status_code":200,"plugin_ver":"","namespace":"ifly_search","status_msg":"Success","type":"local"},"status":"finished"}]}},"header":{"code":0,"message":"Success","sid":"cht000b6763@dx18ff0a422a79a4b560","status":1}}\n```\n**安徽天禾律师事务所的法律意见书主要确认了科大讯飞股份有限公司2023年第三次临时股东大会的召集、召开程序、与会人员资格、表决程序和结果均符合相关法律法规及公司章程的规定，因此股东大会的决议合法有效**。以下是法律意见书的主要内容：\n\n1. **会议程序与召集人资格**：该意见书指出，科大讯飞按照《公司法》等相关规定，通过适当的通知方式召集了股东大会，并且会议召集人资格合法有效[^3^]。\n\n2. **与会人员资格**：参与大会的股东、董事、监事等人员的资格得到了验证，确保所有与会者的参会资格符合规定[^3^]。\n\n3. **表决程序审查**：表决过程包括现场投票和网络投票，均采用记名投票方式进行，保证了表决程序的合法性[^3^]。\n\n4. **表决结果确认**：各项议案的表决结果经过统计，均获得了通过，且没有出现否决议案的情况[^3^]。\n\n5. **结论意见**：基于上述事实，天禾律师认为本次股东大会的所有相关事宜都符合《公司法》、《股东大会规则》等相关法律、法规和《公司章程》的规定，因此股东大会决议合法有效[^3^]。\n\n这份法律意见书不仅为科大讯飞的股东大会提供了法律保障，也向所有利益相关者传递了公司在遵守法律法规方面的透明度和严肃性。它体现了公司在企业治理方面的责任感和规范性，对于维护投资者权益和增强市场信心具有重要作用。\n\n综上所述，安徽天禾律师事务所出具的法律意见书为科大讯飞股份有限公司2023年第三次临时股东大会的合法性和有效性提供了权威认证，确保了公司决策的法律效力和透明度，对公司治理结构和股东权益保护具有重要意义。'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 1, 'completion_tokens': 1, 'total_tokens': 2}, 'created': 1717729241}

**Comment by shyBoy-ico** [comment]
第一次提交的参数 
{'model': 'spark', 'messages': [{'role': 'user', 'content': '\n安徽天禾律师事务所\n\n关于科大讯飞股份有限公司\n\n2023年第三次临时股东大会的法律意见书\n\n天律意2023第3149号\n\n致：科大讯飞股份有限公司\n\n根据《中华人民共和国公司法》（下称“《公司法》”）、《中华人民共和国证券法》（下称“《证券法》”）、中国证券监督管理委员会《上市公司股东大会规则》（下称“《股东大会规则》”）以及《科大讯飞股份有限公司章程》（下称“《公司章程》”）的有关规定，安徽天禾律师事务所接受科大讯飞股份有限公司（下称“公司”）的委托，指派本所费林森、盛建平律师（下称“天禾律师”）出席公司2023年第三次临时股东大会（下称“本次股东大会”），并对本次股东大会相关事项进行见证，出具法律意见。\n\n本法律意见书是天禾律师根据对本次股东大会事实的了解及对我国现行法律、法规和规范性文件的理解而出具的。\n\n天禾律师同意将本法律意见书作为本次股东大会的法定必备文件予以公告，并依法对所出具的法律意见书承担责任。\n\n天禾律师根据《证券法》相关规定的要求，按照律师行业公认的业务标准、道德规范和勤勉尽责精神，对本次股东大会的召集、召开、与会人员资格、表决程序及其他相关法律问题发表如下意见：\n\n一、关于本次股东大会的召集、召开程序及召集人资格\n\n经验证，根据公司第六届董事会第五次会议决议，公司于2023年11月30\n日在《中国证券报》《上海证券报》《证券日报》《证券时报》和巨潮资讯网（http://www.cninfo.com.cn）刊登了《关于召开2023年第三次临时股东大会的通知》。\n\n\n（二）本次股东大会现场会议于2023年12月15日下午2:30在安徽省合\n肥市高新开发区望江西路666号公司科大讯飞A1楼召开，本次股东大会由公司董事会召集，董事长刘庆峰先生主持。\n\n（三）本次股东大会网络投票时间为：2023年12月15日。其中，通过深\n圳证券交易所交易系统进行网络投票的时间为2023年12月15日上午9:15至\n9:25，9:30至11:30和下午13:00-15:00；通过深圳证券交易所互联网投票系统\n进行网络投票的时间为2023年12月15日上午9:15至2023年12月15日下\n午15:00的任意时间。\n\n天禾律师认为，本次股东大会的召集、召开程序符合法律、法规、《股东大会规则》及《公司章程》规定，会议召集人资格合法有效。\n\n二、关于出席本次股东大会会议人员的资格\n\n本次股东大会采取现场表决、网络投票相结合的方式，出席本次股东大会会议人员有：\n\n（一）出席本次股东大会现场会议的股东及股东代理人、通过网络投票表决的股东共计266人，共代表公司股份695,444,756股，占公司股份总数的\n30.0319%，其中：\n\n1、出席现场会议的股东及股东代理人40人，代表公司股份529,683,276\n股，占公司股份总数的22.8737%，均为2023年12月8日下午收市后，在中国\n证券登记结算有限责任公司深圳分公司登记在册的公司股东。股东本人出席\n的，均出示了本人的身份证明文件和持股凭证，股东代理人出席的除出示前述文件外，还出具了授权委托书及代理人的身份证明文件。\n\n2、以网络投票方式参会的股东226人，代表公司股份165,761,480股，占\n公司股份总数的7.1582%，参与网络投票的股东的身份均获得深圳证券交易所系统的认证。\n\n（二）公司部分董事、监事、高级管理人员。\n\n（三）天禾律师。\n\n\n经验证，上述人员参加本次股东大会符合法律、法规、《股东大会规则》和《公司章程》的规定，其与会资格合法有效。\n\n三、关于本次股东大会的表决程序、表决结果\n\n经天禾律师核查，公司本次股东大会对列入通知的议案作了审议，并以记名投票方式进行了现场和网络投票表决。\n\n（一）表决程序\n\n1、经本所律师验证，现场出席本次股东大会的有表决权的股东及股东代理人以记名投票方式对公告中列明的议案进行了表决。\n\n2、参与网络投票的股东通过深圳证券交易系统和互联网投票系统（http://wltp.cninfo.com.cn），以记名投票方式按《深圳证券交易所上市公司股东大会网络投票实施细则》规定的程序对公告中列明的议案进行投票。网络投票结束后，深圳证券信息有限公司向公司提供了本次股东大会网络投票结果。投票表决结束后，公司合并统计了现场投票、网络投票的表决结果。\n\n3、为尊重中小股东利益，提高中小股东对公司股东大会决议的重大事项的参与度，本次股东大会在审议有关议案时，采用中小股东单独计票。\n\n经验证，现场投票、网络投票的表决程序和投票方式、计票统计方式符合《公司法》《股东大会规则》和《公司章程》等规定。\n\n（二）表决结果\n\n经验证，本次股东大会投票结束后，公司合并统计了每项议案的现场投\n票、网络投票的表决结果，公告所列议案均获本次股东大会表决通过。本次股东大会审议通过的议案为：\n\n1、《关于回购注销部分已授予限制性股票的议案》；\n\n2、《独立董事制度》；\n\n3、《关于变更注册资本及修订<公司章程>的议案》。\n\n天禾律师认为：公司本次股东大会的表决程序符合法律法规、《股东大会规则》及《公司章程》的规定，表决结果合法有效。\n\n\n四、结论意见\n\n基于上述事实，天禾律师认为，公司2023年第三次临时股东大会的召集与\n召开、参加会议人员和召集人资格、表决程序与表决结果等相关事宜符合《公司法》《股东大会规则》等相关法律、法规和《公司章程》的规定，本次股东大会决议合法有效。\n\n（以下无正文）\n\n（本页无正文，为《安徽天禾律师事务所关于科大讯飞股份有限公司2023年第三次临时股东大会的法律意见书》签署页，无正文）\n本法律意见书于二〇二三年十二月十五日在安徽省合肥市签字盖章。\n本法律意见书正本一份，副本一份。\n\n安徽天禾律师事务所负责人：卢贤榕\n\n经办律师：费林森\n\n盛建平\n\n'}], 'stream': False, 'conversation_id': 'none'}

第二次提交的参数

{'model': 'spark', 'conversation_id': '376663670:cht000ba156@dx18ff0acc4bfb81a560', 'messages': [{'role': 'user', 'content': '主要讲了什么'}], 'stream': False}

**Comment by Vinlic** [comment]
请更新到0.0.10版本，已修复。
