### ISSUE TITLE
docker部署不能够部署在非8000端口？部署在9000，服务没起来

### ISSUE THREAD

**Issue by Li1Fan** [LLM-Red-Team/spark-free-api#9]
命令如下：
docker run -it -d --init --name spark-free-api -p 9000:9000 -e TZ=Asia/Shanghai vinlic/spark-free-api:latest

**Comment by Li1Fan** [comment]
进入到容器，修改/app/configs/dev/service.yaml即可

**Comment by Vinlic** [comment]
参数写错了，-p 9000:8000才是正确的映射方式

**Comment by Li1Fan** [comment]
谢谢
